//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barangay_Management_Information_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAsset
    {
        public string AccountAssetId { get; set; }
        public string LocationStorageId { get; set; }
        public string AccountId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual LocationStorage LocationStorage { get; set; }
    }
}
