//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barangay_Management_Information_System.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarangayChairman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BarangayChairman()
        {
            this.AssignedOfficials = new HashSet<AssignedOfficial>();
            this.BarangayCounselors = new HashSet<BarangayCounselor>();
        }
    
        public string ChairmanId { get; set; }
        public string ResidentId { get; set; }
        public string SKChairmanId { get; set; }
        public string OfficialTermId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignedOfficial> AssignedOfficials { get; set; }
        public virtual OfficialTerm OfficialTerm { get; set; }
        public virtual ResidentsInformation ResidentsInformation { get; set; }
        public virtual SKChairman SKChairman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarangayCounselor> BarangayCounselors { get; set; }
    }
}
