//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barangay_Management_Information_System.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AccountAsset> AccountAssets { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AssignedOfficial> AssignedOfficials { get; set; }
        public virtual DbSet<AssignedPosition> AssignedPositions { get; set; }
        public virtual DbSet<AuditAction> AuditActions { get; set; }
        public virtual DbSet<AuditTrail> AuditTrails { get; set; }
        public virtual DbSet<BarangayCaptain> BarangayCaptains { get; set; }
        public virtual DbSet<BarangayCounselor> BarangayCounselors { get; set; }
        public virtual DbSet<Deceased> Deceaseds { get; set; }
        public virtual DbSet<HouseHoldAddress> HouseHoldAddresses { get; set; }
        public virtual DbSet<LocationStorage> LocationStorages { get; set; }
        public virtual DbSet<OfficialTerm> OfficialTerms { get; set; }
        public virtual DbSet<ResidentsInformation> ResidentsInformations { get; set; }
        public virtual DbSet<ResidentsLocation> ResidentsLocations { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<SKChairman> SKChairmen { get; set; }
        public virtual DbSet<SKCouncelor> SKCouncelors { get; set; }
        public virtual DbSet<SummonInvolvedResident> SummonInvolvedResidents { get; set; }
        public virtual DbSet<Summon> Summons { get; set; }
        public virtual DbSet<SummonStatu> SummonStatus { get; set; }
        public virtual DbSet<Voter> Voters { get; set; }
    }
}
